spring:
  profiles:
    #动态切换开发或生产环境配置,服务器上的bat已指定 --spring.profiles.active=prod
    active: ${SPRING_PROFILES_ACTIVE:local}
    #active: ${SPRING_PROFILES_ACTIVE:dev}
    #active: ${SPRING_PROFILES_ACTIVE:prod}
